name: CI SonarQube

on:
  pull_request:
    branches:
      - dev # branch default

jobs:
  coverage-sonar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x]

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: interview

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Load .env values from secret
        run: echo "${{ secrets.COVERAGE_TEST }}" > .env

      - name: create link
        run: yarn pretest:e2e

      - name: Run test coverage
        run: yarn test:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
