name: CI SonarQube

on:
  pull_request:
    branches:
      - dev # branch default

jobs:
  coverage-sonar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Run test coverage
        run: pnpm test:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
